from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List
import requests

from app.config import ZAI_API_KEY

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)


class ExpenseItem(BaseModel):
    title: str = ""
    amount: float = 0.0
    category: str = ""


class RequestData(BaseModel):
    user_question: str = ""
    remaining_budget: float = 0.0
    feature_type: str = "chat"
    amount: float = 0.0
    recent_expenses: List[ExpenseItem] = []


@app.get("/")
def root():
    return {"message": "Backend is running"}


def call_glm(prompt: str):
    url = "https://api.ilmu.ai/v1/chat/completions"

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {ZAI_API_KEY}",
    }

    payload = {
        "model": "ilmu-glm-5.1",
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ]
    }

    print("CALL_GLM TEST PAYLOAD:", payload)

    response = requests.post(url, headers=headers, json=payload, timeout=30)

    print("GLM STATUS CODE:", response.status_code)
    print("GLM RESPONSE TEXT:", response.text)

    if response.status_code != 200:
        raise Exception(f"GLM failed: {response.status_code} - {response.text}")

    data = response.json()
    content = data["choices"][0]["message"]["content"]

    if content is None:
        raise Exception(f"GLM content was None. Full body: {response.text}")

    return content


@app.post("/ai/respond")
def respond(data: RequestData):
    budget = data.remaining_budget
    expenses = data.recent_expenses
    total_recent = sum(item.amount for item in expenses)

    # 🔥 TRY REAL AI FIRST
    try:
        prompt = f"""
        User question: {data.user_question}

        Current remaining budget after recent expenses: RM{data.remaining_budget}
        Expenses: {[(e.title, e.amount) for e in data.recent_expenses]}

        Do not subtract recent expenses from the remaining budget again.

        Respond EXACTLY in this format:
        Answer:
        Reason:
        BasedOn:
        """
        glm_text = call_glm(prompt)
        print("RAW GLM TEXT:", repr(glm_text))

        if not glm_text:
            raise Exception("GLM returned empty response")

        lines = [line.strip() for line in glm_text.split("\n") if line.strip()]
        print("PARSED LINES:", lines)

        answer = ""
        reason = ""
        based_on = ""

        i = 0
        while i < len(lines):
            line = lines[i]
            lower_line = line.lower()

            if lower_line == "answer:":
                if i + 1 < len(lines):
                    answer = lines[i + 1]
                    i += 1
            elif lower_line.startswith("answer:"):
                answer = line.split(":", 1)[1].strip()

            elif lower_line == "reason:":
                if i + 1 < len(lines):
                    reason = lines[i + 1]
                    i += 1
            elif lower_line.startswith("reason:"):
                reason = line.split(":", 1)[1].strip()

            elif lower_line == "basedon:":
                if i + 1 < len(lines):
                    based_on = lines[i + 1]
                    i += 1
            elif lower_line.startswith("basedon:"):
                based_on = line.split(":", 1)[1].strip()

            i += 1

        # fallback if parsing fails
        if not answer:
            answer = glm_text
        if not reason:
            reason = "Generated by GLM"
        if not based_on:
            based_on = f"Based on remaining budget RM{budget:.2f}"

        print("PARSED ANSWER:", repr(answer))
        print("PARSED REASON:", repr(reason))
        print("PARSED BASEDON:", repr(based_on))

        return {
            "answer": answer,
            "reason": reason,
            "basedOn": based_on,
            "source": "glm"
        }

    except Exception as e:
        print("GLM ERROR:", str(e))
        glm_failed = True

    # 🔄 FALLBACK LOGIC
    if data.feature_type == "affordability":
        amount = data.amount

        if amount <= budget * 0.3:
            answer = "Yes"
            reason = "This purchase is small relative to your remaining budget."
        elif amount <= budget:
            answer = "Be careful"
            reason = "You can afford it, but it may reduce future flexibility."
        else:
            answer = "No"
            reason = "This exceeds your remaining budget."

        based_on = (
            f"Based on budget RM{budget:.2f}, "
            f"purchase RM{amount:.2f}, "
            f"and {len(expenses)} expense records."
        )

    else:
        if total_recent > budget and budget > 0:
            answer = "Your recent spending may be high."
            reason = "Recent expenses are large relative to your remaining budget."
        elif budget <= 0:
            answer = "Your budget appears exhausted."
            reason = "No remaining budget is available."
        else:
            answer = "Your spending seems manageable."
            reason = "You still have remaining budget."

        based_on = (
            f"Based on budget RM{budget:.2f}, "
            f"recent expenses RM{total_recent:.2f}, "
            f"{len(expenses)} records."
        )

    return {
        "answer": answer,
        "reason": reason,
        "basedOn": based_on,
        "source": "glm_failed" if 'glm_failed' in locals() else "fallback"
    }