from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import requests

from app.config import ZAI_API_KEY

app = FastAPI()


class ExpenseItem(BaseModel):
    title: str = ""
    amount: float = 0.0
    category: str = ""


class RequestData(BaseModel):
    user_question: str = ""
    remaining_budget: float = 0.0
    feature_type: str = "chat"
    amount: float = 0.0
    recent_expenses: List[ExpenseItem] = []


@app.get("/")
def root():
    return {"message": "Backend is running"}


def call_glm(prompt: str):
    url = "https://api.ilmu.ai/v1/chat/completions"

    headers = {
        "Content-Type": "application/json",
        "Authorization": f"Bearer {ZAI_API_KEY}",
    }

    payload = {
        "model": "ilmu-glm-5.1",
        "messages": [
            {"role": "user", "content": f"""User question: {prompt}

            Respond in this EXACT format:

            Answer: <short direct answer>
            Reason: <why based on budget or situation>
            BasedOn: <what data you used>

            Keep it concise."""}
        ],
        "max_tokens": 200
    }

    response = requests.post(url, headers=headers, json=payload, timeout=60)

    if response.status_code != 200:
        raise Exception(f"GLM failed: {response.status_code}")

    data = response.json()

    return data["choices"][0]["message"]["content"]


@app.post("/ai/respond")
def respond(data: RequestData):
    budget = data.remaining_budget
    expenses = data.recent_expenses
    total_recent = sum(item.amount for item in expenses)

    # 🔥 TRY REAL AI FIRST
    try:
        glm_text = call_glm(data.user_question)

        lines = glm_text.split("\n")

        answer = ""
        reason = ""
        based_on = ""

        for line in lines:
            if line.lower().startswith("answer:"):
                answer = line.split(":", 1)[1].strip()
            elif line.lower().startswith("reason:"):
                reason = line.split(":", 1)[1].strip()
            elif line.lower().startswith("basedon:"):
                based_on = line.split(":", 1)[1].strip()

        # fallback if parsing fails
        if not answer:
            answer = glm_text
        if not reason:
            reason = "Generated by GLM"
        if not based_on:
            based_on = f"Based on remaining budget RM{budget:.2f}"

        return {
            "answer": answer,
            "reason": reason,
            "basedOn": based_on,
            "source": "glm"
        }

    except Exception as e:
        print("GLM ERROR:", str(e))

    # 🔄 FALLBACK LOGIC
    if data.feature_type == "affordability":
        amount = data.amount

        if amount <= budget * 0.3:
            answer = "Yes"
            reason = "This purchase is small relative to your remaining budget."
        elif amount <= budget:
            answer = "Be careful"
            reason = "You can afford it, but it may reduce future flexibility."
        else:
            answer = "No"
            reason = "This exceeds your remaining budget."

        based_on = (
            f"Based on budget RM{budget:.2f}, "
            f"purchase RM{amount:.2f}, "
            f"and {len(expenses)} expense records."
        )

    else:
        if total_recent > budget and budget > 0:
            answer = "Your recent spending may be high."
            reason = "Recent expenses are large relative to your remaining budget."
        elif budget <= 0:
            answer = "Your budget appears exhausted."
            reason = "No remaining budget is available."
        else:
            answer = "Your spending seems manageable."
            reason = "You still have remaining budget."

        based_on = (
            f"Based on budget RM{budget:.2f}, "
            f"recent expenses RM{total_recent:.2f}, "
            f"{len(expenses)} records."
        )

    return {
        "answer": answer,
        "reason": reason,
        "basedOn": based_on,
        "source": "fallback"
    }